/*++++++++++++++++++++++++++++++++++++++++++++++++*
 * CONFIGURACION DE MESES PARA RENOVAR POR SUBKIT
 *++++++++++++++++++++++++++++++++++++++++++++++++*/

ALTER TABLE RHEKT.UNI_CAT_CIA DROP COLUMN FIMESESRENOV;

ALTER TABLE RHEKT.TASUBKITSXKIT ADD 
	(
		FIMESESRENOV	NUMBER(2) DEFAULT 6 NOT NULL
	);
  
ALTER TABLE RHEKT.TASUBKITS ADD
  (
    FIREPOSICION  NUMBER(1) DEFAULT 0 NOT NULL
  );

/*+++++++++++++++++++++++++++++++++++*
 * TABLA DE ESTATUS DE REPOSICIONES
 *+++++++++++++++++++++++++++++++++++*/
 
CREATE TABLE RHEKT.TAESTATUSREPOSICION
(
  FIESTATUSREPOSICION NUMBER(3) NOT NULL,
  FCDESCRIPCION       VARCHAR2(50 CHAR) NOT NULL
)
  TABLESPACE TBS_RHEKT_CAT_DAT
  LOGGING;

CREATE UNIQUE INDEX RHEKT.PK_TAESTATUSREPOSICION ON RHEKT.TAESTATUSREPOSICION
  (FIESTATUSREPOSICION)
  LOGGING
	TABLESPACE TBS_RHEKT_CAT_IDX;

ALTER TABLE RHEKT.TAESTATUSREPOSICION
  ADD CONSTRAINT PK_TAESTATUSREPOSICION PRIMARY KEY (FIESTATUSREPOSICION) USING INDEX RHEKT.PK_TAESTATUSREPOSICION;
  
/*+++++++++++++++++++++++++++++++++++*
 * TABLA DE REPOSICIONES
 *+++++++++++++++++++++++++++++++++++*/
 
CREATE TABLE RHEKT.TAREPOSICIONES
(
  FIFOLIOREPOSICION   NUMBER(10) NOT NULL,
  FIEMPLEADO          NUMBER(10) NOT NULL,
  FCCORREO            VARCHAR2(50 CHAR) NOT NULL,
  FCTELEFONO          VARCHAR2(30 CHAR) NOT NULL,
  FCMOTIVO            VARCHAR2(50 CHAR) NOT NULL,
  FCMENSAJE           VARCHAR2(300 CHAR) NOT NULL,
  FIEMPLEADOAUTORIZA  NUMBER(10) NOT NULL,
  FCOBSERVACIONES     VARCHAR2(300 CHAR) NOT NULL,
  FIPEDIDO            NUMBER(10) NOT NULL,
  FISUCURSAL          NUMBER(10) NOT NULL,
  FNPRECIO            NUMBER(10, 2) NOT NULL,
  FIIDSUBKIT          NUMBER(10) NOT NULL,
  FIESTATUSREPOSICION NUMBER(3) NOT NULL
)
  TABLESPACE TBS_RHEKT_OPE_DAT
  LOGGING;

CREATE UNIQUE INDEX RHEKT.PK_TAREPOSICIONES ON RHEKT.TAREPOSICIONES
  (FIFOLIOREPOSICION)
  LOGGING
	TABLESPACE TBS_RHEKT_OPE_IDX;
  
ALTER TABLE RHEKT.TAREPOSICIONES ADD 
(
  CONSTRAINT PK_TAREPOSICIONES PRIMARY KEY (FIFOLIOREPOSICION) USING INDEX RHEKT.PK_TAREPOSICIONES,
  CONSTRAINT FK_TAREPOSICIONES_01 FOREIGN KEY (FIIDSUBKIT) REFERENCES RHEKT.TASUBKITS(FIIDSUBKIT),
  CONSTRAINT FK_TAREPOSICIONES_02 FOREIGN KEY (FIESTATUSREPOSICION) REFERENCES RHEKT.TAESTATUSREPOSICION(FIESTATUSREPOSICION)
);

CREATE INDEX RHEKT.IX_TAREPOSICIONES_01 ON RHEKT.TAREPOSICIONES
  (FIEMPLEADO)
  LOGGING
  TABLESPACE TBS_RHEKT_OPE_IDX;
  
CREATE SEQUENCE RHEKT.SEFOLIOREPOSICION
  START WITH 1
  MAXVALUE 99999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

/*+++++++++++++++++++++++++++++++++++*
 * CATALOGO DE TIPO DE SOLICITUD
 *+++++++++++++++++++++++++++++++++++*/
CREATE TABLE RHEKT.TATIPOSOLICITUD
(
  FIIDTIPOSOLICITUD  NUMBER(3) NOT NULL,
  FCDESCRIPCION      VARCHAR2(30 CHAR) NOT NULL
)
  TABLESPACE TBS_RHEKT_CAT_DAT
  LOGGING;

CREATE UNIQUE INDEX RHEKT.PK_TATIPOSOLICITUD ON RHEKT.TATIPOSOLICITUD
  (FIIDTIPOSOLICITUD)
  LOGGING
	TABLESPACE TBS_RHEKT_CAT_IDX;

ALTER TABLE RHEKT.TATIPOSOLICITUD
  ADD CONSTRAINT PK_TATIPOSOLICITUD PRIMARY KEY (FIIDTIPOSOLICITUD) USING INDEX RHEKT.PK_TATIPOSOLICITUD;

INSERT INTO RHEKT.TATIPOSOLICITUD(FIIDTIPOSOLICITUD, FCDESCRIPCION) VALUES (1, 'ORDINARIA');
INSERT INTO RHEKT.TATIPOSOLICITUD(FIIDTIPOSOLICITUD, FCDESCRIPCION) VALUES (2, 'EXTRAORDINARIA CON COSTO');
INSERT INTO RHEKT.TATIPOSOLICITUD(FIIDTIPOSOLICITUD, FCDESCRIPCION) VALUES (3, 'EXTRAORDINARIA SIN COSTO');
COMMIT;

/*+++++++++++++++++++++++++++++++++++*
 * SE AGREGAN LOS CAMPOS PARA EL REPORTE GENERAL
 *+++++++++++++++++++++++++++++++++++*/
 
ALTER TABLE RHEKT.UNI_INVENTARIO_C_SKU ADD
(
  FIIDTIPOSOLICITUD   NUMBER(3)  DEFAULT 1 NOT NULL,
  FIEMPLEADOAUTORIZA  NUMBER(10) DEFAULT 0 NOT NULL
);

ALTER TABLE RHEKT.UNI_INVENTARIO_C_SKU
  ADD CONSTRAINT FK_UNIINVENTARIOCSKU_01 FOREIGN KEY (FIIDTIPOSOLICITUD) REFERENCES RHEKT.TATIPOSOLICITUD(FIIDTIPOSOLICITUD);
  