CREATE TABLE RHEKT.TASOLICSININVENTARIO(
  FIIDSOLICITUD       NUMBER(20) NOT NULL,
  FIEMPLEADONUM       NUMBER(10) NOT NULL,
  FIPERIODO           NUMBER(6) NOT NULL,
  FDFECHASOLICITUD    DATE NOT NULL,
  FIIDSUBKIT          NUMBER(5) NOT NULL,
  FISKU               NUMBER(10) NOT NULL,
  FIIDCEDIS           NUMBER(5) NOT NULL,  
  FICANTIDAD          NUMBER(3) NOT NULL,
  FIORDEN             NUMBER(3) NOT NULL
)
  TABLESPACE TBS_RHEKT_OPE_DAT
  LOGGING;

CREATE UNIQUE INDEX RHEKT.PK_TASOLICSININVENTARIO ON RHEKT.TASOLICSININVENTARIO
  (FIIDSOLICITUD)
  LOGGING
	TABLESPACE TBS_RHEKT_OPE_IDX;

ALTER TABLE RHEKT.TASOLICSININVENTARIO ADD 
(
  CONSTRAINT PK_TASOLICSININVENTARIO PRIMARY KEY (FIIDSOLICITUD) USING INDEX RHEKT.PK_TASOLICSININVENTARIO,
  CONSTRAINT FK_TASOLICSININVENTARIO_01 FOREIGN KEY (FIIDSUBKIT) REFERENCES RHEKT.TASUBKITS(FIIDSUBKIT),
  CONSTRAINT FK_TASOLICSININVENTARIO_02 FOREIGN KEY (FISKU) REFERENCES RHEKT.UNI_PIEZA_UNIFORME(SKU),
  CONSTRAINT FK_TASOLICSININVENTARIO_03 FOREIGN KEY (FIIDCEDIS) REFERENCES RHEKT.TACEDIS(FIIDCEDIS)
);

CREATE INDEX RHEKT.IX_TASOLICSININVENTARIO ON RHEKT.TASOLICSININVENTARIO
  (FIPERIODO)
  LOGGING
	TABLESPACE TBS_RHEKT_OPE_IDX;
  
CREATE SEQUENCE RHEKT.SESOLICSININVENTARIO
  START WITH 1
  MAXVALUE 99999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;