/*************************************************************
Proyecto: Uniformes
Descripción: Creación esquema para configuración de uniformes por CeDis
Parámetros de entrada: Ninguno.
Parámetros de salida: Ninguno.
Parámetros de entrada-salida: Ninguno.
Valor de retorno: Resultado de ejecucion de cada línea.
Precondiciones: Ninguna.
Creador: Othoniel Garcia Gonzalez
Fecha de creacion: Septiembre 2014
*************************************************************/

/*++++++++++++++++++++++++++++++++
 Catálogo de kits de uniformes   +
 ++++++++++++++++++++++++++++++++*/

CREATE TABLE RHEKT.TAKITUNIFORMES
(
  FIIDKIT         NUMBER(5)        NOT NULL,
  FCDESCRIPCION   VARCHAR(50 CHAR) NOT NULL,
  FISEMANASDESCTO NUMBER(3)        NOT NULL
)
TABLESPACE TBS_RHEKT_CAT_DAT
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX RHEKT.PK_TAKITUNIFORMES ON RHEKT.TAKITUNIFORMES(FIIDKIT ASC)
TABLESPACE TBS_RHEKT_CAT_IDX
LOGGING;

ALTER TABLE RHEKT.TAKITUNIFORMES ADD CONSTRAINT PK_TAKITUNIFORMES PRIMARY KEY(FIIDKIT)
USING INDEX RHEKT.PK_TAKITUNIFORMES;

/*++++++++++++++++++++++++++++++++
 Catálogo de Subkits             +
 ++++++++++++++++++++++++++++++++*/
 
CREATE TABLE RHEKT.TASUBKITS
(
  FIIDSUBKIT    NUMBER(5)         NOT NULL,
  FCDESCRIPCION VARCHAR(50 CHAR)  NOT NULL,
  FICANTIDAD    NUMBER(5)         NOT NULL,
  FNPRECIO      NUMBER(10, 2)     NOT NULL
)
TABLESPACE TBS_RHEKT_CAT_DAT
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX RHEKT.PK_TASUBKITS ON RHEKT.TASUBKITS(FIIDSUBKIT ASC)
TABLESPACE TBS_RHEKT_CAT_IDX
LOGGING;

ALTER TABLE RHEKT.TASUBKITS ADD CONSTRAINT PK_TASUBKITS PRIMARY KEY(FIIDSUBKIT)
USING INDEX RHEKT.PK_TASUBKITS;

/*++++++++++++++++++++++++++++++++
 Relación kit - subkit           +
 ++++++++++++++++++++++++++++++++*/
CREATE TABLE RHEKT.TASUBKITSXKIT
(
  FIIDKIT     NUMBER(5) NOT NULL,
  FIIDSUBKIT  NUMBER(5) NOT NULL
)
TABLESPACE TBS_RHEKT_CAT_DAT
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX RHEKT.PK_TASUBKITSXKIT ON RHEKT.TASUBKITSXKIT
(
  FIIDKIT     ASC,
  FIIDSUBKIT  ASC
)
TABLESPACE TBS_RHEKT_CAT_IDX
LOGGING;

ALTER TABLE RHEKT.TASUBKITSXKIT ADD CONSTRAINT PK_TASUBKITSXKIT PRIMARY KEY (FIIDKIT, FIIDSUBKIT)
USING INDEX RHEKT.PK_TASUBKITSXKIT;

ALTER TABLE RHEKT.TASUBKITSXKIT ADD
(
  CONSTRAINT FK_TASUBKITSXKIT_01 FOREIGN KEY (FIIDKIT) REFERENCES RHEKT.TAKITUNIFORMES(FIIDKIT),
  CONSTRAINT FK_TASUBKITSXKIT_02 FOREIGN KEY (FIIDSUBKIT)  REFERENCES RHEKT.TASUBKITS(FIIDSUBKIT)
);

/*++++++++++++++++++++++++++++++++
 Relación subkit - piezas        +
 ++++++++++++++++++++++++++++++++*/

CREATE TABLE RHEKT.TASKUSXSUBKIT
(
  FIIDSUBKIT NUMBER(5)  NOT NULL,
  FISKU      NUMBER(10) NOT NULL
)
TABLESPACE TBS_RHEKT_CAT_DAT
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX RHEKT.PK_TASKUSXSUBKIT ON RHEKT.TASKUSXSUBKIT
(
  FIIDSUBKIT ASC,
  FISKU      ASC
)
TABLESPACE TBS_RHEKT_CAT_IDX
LOGGING;

ALTER TABLE RHEKT.TASKUSXSUBKIT ADD CONSTRAINT PK_TASKUSXSUBKIT PRIMARY KEY (FIIDSUBKIT, FISKU)
USING INDEX RHEKT.PK_TASKUSXSUBKIT;

ALTER TABLE RHEKT.TASKUSXSUBKIT ADD 
(
    CONSTRAINT FK_TASKUSXSUBKIT_01 FOREIGN KEY (FIIDSUBKIT) REFERENCES RHEKT.TASUBKITS(FIIDSUBKIT),
    CONSTRAINT FK_TASKUSXSUBKIT_02 FOREIGN KEY (FISKU)      REFERENCES RHEKT.UNI_PIEZA_UNIFORME(SKU)
);


/*++++++++++++++++++++++++++++++++++++++++++++++++++
 Relación de Función SAP - Unidad de Negocio - Kit +
 ++++++++++++++++++++++++++++++++++++++++++++++++++*/

CREATE TABLE RHEKT.TAFUNCIONESXNEGOCIO
(
    FINEGOCIO       NUMBER(5)   NOT NULL,
    FIIDFUNCION     NUMBER(10)  NOT NULL,
    FIPARCIAL       NUMBER(1)   NOT NULL,
    FIIDKIT         NUMBER(5)   NOT NULL
)
TABLESPACE TBS_RHEKT_CAT_DAT
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX RHEKT.PK_TAFUNCIONESXNEGOCIO ON RHEKT.TAFUNCIONESXNEGOCIO
(
    FINEGOCIO   ASC,
    FIIDFUNCION ASC,
    FIPARCIAL   ASC
)
TABLESPACE TBS_RHEKT_CAT_IDX
LOGGING;

ALTER TABLE RHEKT.TAFUNCIONESXNEGOCIO ADD CONSTRAINT PK_TAFUNCIONESXNEGOCIO PRIMARY KEY (FINEGOCIO, FIIDFUNCION, FIPARCIAL)
USING INDEX RHEKT.PK_TAFUNCIONESXNEGOCIO;

ALTER TABLE RHEKT.TAFUNCIONESXNEGOCIO ADD 
(
    CONSTRAINT FK_TAFUNCIONESXNEGOCIO_01 FOREIGN KEY (FINEGOCIO)      REFERENCES RHEKT.UNI_CAT_CIA(ID),
    CONSTRAINT FK_TAFUNCIONESXNEGOCIO_02 FOREIGN KEY (FIIDFUNCION)  REFERENCES RHEKT.UNI_CAT_FUNCION(ID),
    CONSTRAINT FK_TAFUNCIONESXNEGOCIO_03 FOREIGN KEY (FIIDKIT)      REFERENCES RHEKT.TAKITUNIFORMES(FIIDKIT)
);

/*++++++++++++++++++++++++++++++++++++++++++++++++++
 Catálogo de Centros de Distribución                   +
 ++++++++++++++++++++++++++++++++++++++++++++++++++*/
CREATE TABLE RHEKT.TACEDIS
(
  FIIDCEDIS NUMBER(5)        NOT NULL,
  FCNOMBRECEDIS VARCHAR(100 CHAR) NOT NULL
)
TABLESPACE TBS_RHEKT_CAT_DAT
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX RHEKT.PK_TACEDIS ON RHEKT.TACEDIS(FIIDCEDIS ASC)
TABLESPACE TBS_RHEKT_CAT_IDX
LOGGING;

ALTER TABLE RHEKT.TACEDIS ADD CONSTRAINT PK_TACEDIS PRIMARY KEY (FIIDCEDIS)
USING INDEX RHEKT.PK_TACEDIS;

/*++++++++++++++++++++++++++++++++++++++++++++++++++
 Catálogo de relación de kits x CDs                +
 ++++++++++++++++++++++++++++++++++++++++++++++++++*/
CREATE TABLE RHEKT.TAKITXCEDIS
(
  FIIDCEDIS NUMBER(5)   NOT NULL,
  FIIDKIT   NUMBER(5)   NOT NULL
)
TABLESPACE TBS_RHEKT_CAT_DAT
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX RHEKT.PK_TAKITXCEDIS ON RHEKT.TAKITXCEDIS
(
    FIIDCEDIS ASC,
    FIIDKIT ASC
)
TABLESPACE TBS_RHEKT_CAT_IDX
LOGGING;


ALTER TABLE RHEKT.TAKITXCEDIS ADD CONSTRAINT PK_TAKITXCEDIS PRIMARY KEY (FIIDCEDIS, FIIDKIT)
USING INDEX RHEKT.PK_TAKITXCEDIS;

ALTER TABLE RHEKT.TAKITXCEDIS ADD
(
    CONSTRAINT FK_TAKITXCEDIS_01 FOREIGN KEY (FIIDCEDIS)   REFERENCES RHEKT.TACEDIS(FIIDCEDIS),
    CONSTRAINT FK_TAKITXCEDIS_02 FOREIGN KEY (FIIDKIT)     REFERENCES RHEKT.TAKITUNIFORMES(FIIDKIT)
);

/*++++++++++++++++++++++++++++++++++++++++++++++++++
 Catálogo de Tiendas                               +
 ++++++++++++++++++++++++++++++++++++++++++++++++++*/
CREATE TABLE RHEKT.TASUCURSALES
(
	FISUCURSAL           NUMBER(5) NOT NULL ,
	FCDESCRIPCION        VARCHAR2(100 CHAR) NOT NULL ,
	FCDIRIP              VARCHAR2(20 CHAR) NOT NULL ,
	FIIDCDISTRIBUCION    NUMBER(5) NOT NULL ,
	FIIDFORMADOR         NUMBER(10) NOT NULL 
)
TABLESPACE TBS_RHEKT_CAT_DAT
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX RHEKT.PK_TASUCURSALES ON RHEKT.TASUCURSALES
(FISUCURSAL   ASC)
	LOGGING
	TABLESPACE TBS_RHEKT_CAT_IDX;

ALTER TABLE RHEKT.TASUCURSALES
	ADD CONSTRAINT  PK_TASUCURSALES PRIMARY KEY (FISUCURSAL)   USING INDEX RHEKT.PK_TASUCURSALES;

ALTER TABLE RHEKT.TASUCURSALES 
	ADD CONSTRAINT FK_TASUCURSALES_01 FOREIGN KEY (FIIDCDISTRIBUCION) REFERENCES RHEKT.TACEDIS (FIIDCEDIS);

/*++++++++++++++++++++++++++++++++++++++++++++++++++
 Tabla de precios del pedido                       +
 ++++++++++++++++++++++++++++++++++++++++++++++++++*/
 
ALTER TABLE RHEKT.UNI_PRECIO_PEDIDO ADD
(
  FISEMANASDESCTO NUMBER(5) DEFAULT 8 NOT NULL 
);

CREATE UNIQUE INDEX RHEKT.PK_UNI_PRECIO_PEDIDO ON RHEKT.UNI_PRECIO_PEDIDO
	(FOLIO_UNIFICADO ASC, NUM_PEDIDO ASC)
	LOGGING
	TABLESPACE TBS_RHEKT_OPE_IDX;

ALTER TABLE RHEKT.UNI_PRECIO_PEDIDO ADD
	CONSTRAINT PK_UNI_PRECIO_PEDIDO PRIMARY KEY (FOLIO_UNIFICADO, NUM_PEDIDO)
	USING INDEX RHEKT.PK_UNI_PRECIO_PEDIDO;