/*************************************************************
Proyecto: Uniformes
Descripción: Creacion esquema el sistema de uniformes para regionales
Parametros de entrada: Ninguno.
Parametros de salida: Ninguno.
Parametros de entrada-salida: Ninguno.
Valor de retorno: Resultado de ejecucion de cada linea.
Precondiciones: Ninguna.
Creador: Othoniel Garcia Gonzalez
Fecha de creacion: Septiembre 2014
*************************************************************/

/*------------------------------------------------------------*
 *                    TABLAS CATALOGOS                        *
 *------------------------------------------------------------*
/******************************************
 * Tabla de estatus general               *
 ******************************************/
CREATE TABLE RHEKT.TACATSTATUSGRAL
(
	FIIDSTATUSGRAL		NUMBER(5) 			NOT NULL,
	FCDESCRIPCION		VARCHAR(50 CHAR) 	NOT NULL
)
TABLESPACE TBS_RHEKT_CAT_DAT
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX RHEKT.PK_TACATSTATUSGRAL ON RHEKT.TACATSTATUSGRAL(FIIDSTATUSGRAL ASC)
TABLESPACE TBS_RHEKT_CAT_IDX
LOGGING;

ALTER TABLE RHEKT.TACATSTATUSGRAL ADD CONSTRAINT PK_TACATSTATUSGRAL PRIMARY KEY (FIIDSTATUSGRAL)
USING INDEX RHEKT.PK_TACATSTATUSGRAL;

/******************************************
 * Tabla de estatus por detalle           *
 ******************************************/
CREATE TABLE RHEKT.TACATSTATUSDETALLE
(
	FIIDSTATUSDETALLE	NUMBER(5) 			NOT NULL,
	FCDESCRIPCION		VARCHAR(50 CHAR) 	NOT NULL
)
TABLESPACE TBS_RHEKT_CAT_DAT
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX RHEKT.PK_TACATSTATUSDETALLE ON RHEKT.TACATSTATUSDETALLE(FIIDSTATUSDETALLE ASC)
TABLESPACE TBS_RHEKT_CAT_IDX
LOGGING;

ALTER TABLE RHEKT.TACATSTATUSDETALLE ADD CONSTRAINT PK_TACATSTATUSDETALLE PRIMARY KEY (FIIDSTATUSDETALLE)
USING INDEX RHEKT.PK_TACATSTATUSDETALLE;

/******************************************
 * Tabla de estatus de uniforme asignado  *
 ******************************************/
CREATE TABLE RHEKT.TACATSTATUSASIGN
(
	FIIDSTATUSASIGN		NUMBER(3)			NOT NULL,
	FCDESCRIPCION		VARCHAR(50 CHAR)	NOT NULL
)
TABLESPACE TBS_RHEKT_CAT_DAT
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX RHEKT.PK_TACATSTATUSASIGN ON RHEKT.TACATSTATUSASIGN(FIIDSTATUSASIGN ASC)
TABLESPACE TBS_RHEKT_CAT_IDX
LOGGING;

ALTER TABLE RHEKT.TACATSTATUSASIGN ADD CONSTRAINT PK_TACATSTATUSASIGN PRIMARY KEY (FIIDSTATUSASIGN)
USING INDEX RHEKT.PK_TACATSTATUSASIGN;

/*------------------------------------------------------------*
 *                   TABLAS OPERATIVAS                        *
 *------------------------------------------------------------*
/******************************************
 * Tabla de solicitudes de stock          *
 ******************************************/
CREATE TABLE RHEKT.TASOLICITUDSTOCK
(
	FIIDSOLICITUD		NUMBER(10)	NOT NULL,
	FIEMPLEADONUM		NUMBER(10)	NOT NULL,
	FDFECHASOLICITUD	DATE		NOT NULL,
	FIIDESTATUS			NUMBER(5)	NOT NULL,
	FITIENDARECEPTORA	NUMBER(5)	NOT NULL
)
TABLESPACE TBS_RHEKT_OPE_DAT
LOGGING;

CREATE UNIQUE INDEX RHEKT.PK_TASOLICITUDSTOCK ON RHEKT.TASOLICITUDSTOCK(FIIDSOLICITUD ASC)
TABLESPACE TBS_RHEKT_OPE_IDX
LOGGING;

ALTER TABLE RHEKT.TASOLICITUDSTOCK ADD CONSTRAINT PK_TASOLICITUDSTOCK PRIMARY KEY (FIIDSOLICITUD)
USING INDEX RHEKT.PK_TASOLICITUDSTOCK;

ALTER TABLE RHEKT.TASOLICITUDSTOCK ADD CONSTRAINT FK_TASOLICITUDSTOCK_01 FOREIGN KEY (FIIDESTATUS)
REFERENCES RHEKT.TACATSTATUSGRAL(FIIDSTATUSGRAL);

/********************************************
 * Tabla de detalle de solicitudes de stock *
 ********************************************/
CREATE TABLE RHEKT.TASOLICSTOCKDETALLE
(
 	FIIDSOLICDETALLE	NUMBER(10)	NOT NULL,
 	FIIDSOLICITUD		NUMBER(10)	NOT NULL,
 	FIPEDIDOTIENDA		NUMBER(10)	NOT NULL,
 	FISKU				NUMBER(10)	NOT NULL,
 	FICANTIDAD			NUMBER(3)	NOT NULL,
 	FIIDSTATUSDETALLE	NUMBER(5)	NOT NULL
)
TABLESPACE TBS_RHEKT_OPE_DAT
LOGGING;

CREATE UNIQUE INDEX RHEKT.PK_TASOLICSTOCKDETALLE ON RHEKT.TASOLICSTOCKDETALLE(FIIDSOLICDETALLE ASC)
TABLESPACE TBS_RHEKT_OPE_IDX
LOGGING;

ALTER TABLE RHEKT.TASOLICSTOCKDETALLE ADD CONSTRAINT PK_TASOLICSTOCKDETALLE PRIMARY KEY (FIIDSOLICDETALLE)
USING INDEX RHEKT.PK_TASOLICSTOCKDETALLE;

ALTER TABLE RHEKT.TASOLICSTOCKDETALLE ADD
(
	CONSTRAINT FK_TASOLICSTOCKDETALLE_01 FOREIGN KEY (FIIDSOLICITUD) REFERENCES RHEKT.TASOLICITUDSTOCK(FIIDSOLICITUD),
	CONSTRAINT FK_TASOLICSTOCKDETALLE_02 FOREIGN KEY (FISKU)		 REFERENCES RHEKT.UNI_PIEZA_UNIFORME(SKU)
);

/********************************************
 * Tabla de histórico de estatus            *
 ********************************************/
CREATE TABLE RHEKT.TAHISTSOLICITUDSTOCK
(
	FIIDHISTORICO		NUMBER(20)			NOT NULL,
	FIIDSOLICDETALLE	NUMBER(10)			NOT NULL,
	FDFECHA 			DATE				NOT NULL,
	FIESTATUSANT		NUMBER(5)			NOT NULL,
	FINVOESTATUS		NUMBER(5)			NOT NULL,
	FCOBSERVACIONES		VARCHAR(100 CHAR)	NOT NULL
)
TABLESPACE TBS_RHEKT_OPE_DAT
LOGGING;

CREATE UNIQUE INDEX RHEKT.PK_TAHISTSOLICITUDSTOCK ON RHEKT.TAHISTSOLICITUDSTOCK (FIIDHISTORICO ASC)
TABLESPACE TBS_RHEKT_OPE_IDX
LOGGING;

ALTER TABLE RHEKT.TAHISTSOLICITUDSTOCK ADD CONSTRAINT PK_TAHISTSOLICITUDSTOCK PRIMARY KEY (FIIDHISTORICO)
USING INDEX RHEKT.PK_TAHISTSOLICITUDSTOCK;

ALTER TABLE RHEKT.TAHISTSOLICITUDSTOCK ADD
(
	CONSTRAINT FK_TAHISTSOLICITUDSTOCK_01 FOREIGN KEY (FIIDSOLICDETALLE) REFERENCES RHEKT.TASOLICSTOCKDETALLE(FIIDSOLICDETALLE),
	CONSTRAINT FK_TAHISTSOLICITUDSTOCK_02 FOREIGN KEY (FIESTATUSANT)	 REFERENCES RHEKT.TACATSTATUSDETALLE(FIIDSTATUSDETALLE),
	CONSTRAINT FK_TAHISTSOLICITUDSTOCK_03 FOREIGN KEY (FINVOESTATUS)	 REFERENCES RHEKT.TACATSTATUSDETALLE(FIIDSTATUSDETALLE)
);

/********************************************
 * Tabla de remisiones                      *
 ********************************************/

CREATE TABLE RHEKT.TAREMISION
(
	FINUMREMISION		NUMBER(20)		NOT NULL,
	FIIDSOLICDETALLE 	NUMBER(10)		NOT NULL,
	FICANTIDAD			NUMBER(5)		NOT NULL,
	FIEMPLEADORECIBE	NUMBER(10)		NOT NULL,
	FDFECHA 			DATE			NOT NULL
)
TABLESPACE TBS_RHEKT_OPE_DAT
LOGGING;

CREATE UNIQUE INDEX RHEKT.PK_TAREMISION ON RHEKT.TAREMISION (FINUMREMISION ASC, FIIDSOLICDETALLE ASC)
TABLESPACE TBS_RHEKT_OPE_IDX
LOGGING;

ALTER TABLE RHEKT.TAREMISION ADD CONSTRAINT PK_TAREMISION PRIMARY KEY (FINUMREMISION, FIIDSOLICDETALLE)
USING INDEX RHEKT.PK_TAREMISION;

ALTER TABLE RHEKT.TAREMISION ADD 
	CONSTRAINT FK_TAREMISION_01 FOREIGN KEY (FIIDSOLICDETALLE) REFERENCES RHEKT.TASOLICSTOCKDETALLE(FIIDSOLICDETALLE); 

/********************************************
 * Tabla de inventario en stock             *
 ********************************************/
CREATE TABLE RHEKT.TAINVENTARIOEMP
(
	FIEMPLEADONUM	NUMBER(10)	NOT NULL,
	FISKU			NUMBER(20)	NOT NULL,
	FIINVNETO		NUMBER(10)	NOT NULL,
	FIINVASIGNADO	NUMBER(10)	NOT NULL,
	FIINVENPROCESO	NUMBER(10)	NOT NULL
)
TABLESPACE TBS_RHEKT_OPE_DAT
LOGGING;

CREATE UNIQUE INDEX RHEKT.PK_TAINVENTARIOEMP ON RHEKT.TAINVENTARIOEMP(FIEMPLEADONUM ASC, FISKU ASC)
TABLESPACE TBS_RHEKT_OPE_IDX
LOGGING;

ALTER TABLE RHEKT.TAINVENTARIOEMP ADD CONSTRAINT PK_TAINVENTARIOEMP PRIMARY KEY (FIEMPLEADONUM, FISKU)
USING INDEX RHEKT.PK_TAINVENTARIOEMP;

ALTER TABLE RHEKT.TAINVENTARIOEMP ADD
	CONSTRAINT FK_TAINVENTARIOEMP_01 FOREIGN KEY (FISKU) REFERENCES RHEKT.UNI_PIEZA_UNIFORME(SKU);

/********************************************
 * Tabla de asignación de uniforme          *
 ********************************************/
CREATE TABLE RHEKT.TAASIGNAUNIFORME
(
	FIIDASIGNACION	NUMBER(20)	NOT NULL,
	FIEMPENTREGA	NUMBER(10)	NOT NULL,
	FIEMPRECIBE		NUMBER(10) 	NOT NULL,
	FISKU			NUMBER(20)	NOT NULL,
	FICANTIDAD		NUMBER(3)	NOT NULL,
	FIPRECIOEMP		NUMBER(10)	NOT NULL,
	FISEMANASDESCTO	NUMBER(3)	NOT NULL,
	FIIDESTATUS		NUMBER(3)	NOT NULL,
	FINEGOCIOID		NUMBER(5)	NOT NULL,
	FDFECHA 		DATE		NOT NULL,
	FDFECHAENTREGA	DATE		NOT NULL
)
TABLESPACE TBS_RHEKT_OPE_DAT
LOGGING;

CREATE UNIQUE INDEX RHEKT.PK_TAASIGNAUNIFORME ON RHEKT.TAASIGNAUNIFORME(FIIDASIGNACION ASC)
TABLESPACE TBS_RHEKT_OPE_IDX
LOGGING;

ALTER TABLE RHEKT.TAASIGNAUNIFORME ADD CONSTRAINT PK_TAASIGNAUNIFORME PRIMARY KEY (FIIDASIGNACION)
USING INDEX RHEKT.PK_TAASIGNAUNIFORME;

ALTER TABLE RHEKT.TAASIGNAUNIFORME ADD 
(
	CONSTRAINT FK_TAASIGNAUNIFORME_01 FOREIGN KEY (FISKU) REFERENCES RHEKT.UNI_PIEZA_UNIFORME(SKU),
	CONSTRAINT FK_TAASIGNAUNIFORME_02 FOREIGN KEY (FIIDESTATUS) REFERENCES RHEKT.TACATSTATUSASIGN(FIIDSTATUSASIGN),
	CONSTRAINT FK_TAASIGNAUNIFORME_03 FOREIGN KEY (FINEGOCIOID) REFERENCES RHEKT.UNI_CAT_CIA(ID)
);

/*------------------------------------------------------------*
 *                       SECUENCIAS                           *
 *------------------------------------------------------------*/

CREATE SEQUENCE RHEKT.SEQIDSOLICITUD
  START WITH 1
  MAXVALUE 99999999999999999999
  MINVALUE 1
  NOCYCLE
  ORDER;

CREATE SEQUENCE RHEKT.SEQIDSOLICDETALLE
  START WITH 1
  MAXVALUE 99999999999999999999
  MINVALUE 1
  NOCYCLE
  ORDER;

CREATE SEQUENCE RHEKT.SEQIDHISTORICO
  START WITH 1
  MAXVALUE 99999999999999999999
  MINVALUE 1
  NOCYCLE
  ORDER;

CREATE SEQUENCE RHEKT.SEQIDASIGNACION
  START WITH 1
  MAXVALUE 99999999999999999999
  MINVALUE 1
  NOCYCLE
  ORDER;