DROP TABLE RHEKT.TAASIGNAUNIFORME CASCADE CONSTRAINTS PURGE;
DROP TABLE RHEKT.TAINVENTARIOEMP CASCADE CONSTRAINTS PURGE;
DROP TABLE RHEKT.TAREMISION CASCADE CONSTRAINTS PURGE;
DROP TABLE RHEKT.TAHISTSOLICITUDSTOCK CASCADE CONSTRAINTS PURGE;
DROP TABLE RHEKT.TASOLICSTOCKDETALLE CASCADE CONSTRAINTS PURGE;
DROP TABLE RHEKT.TASOLICITUDSTOCK CASCADE CONSTRAINTS PURGE;
DROP TABLE RHEKT.TACATSTATUSASIGN CASCADE CONSTRAINTS PURGE;
DROP TABLE RHEKT.TACATSTATUSDETALLE CASCADE CONSTRAINTS PURGE;
DROP TABLE RHEKT.TACATSTATUSGRAL CASCADE CONSTRAINTS PURGE;

DROP SEQUENCE RHEKT.SEQIDSOLICITUD;
DROP SEQUENCE RHEKT.SEQIDSOLICDETALLE;
DROP SEQUENCE RHEKT.SEQIDHISTORICO;
DROP SEQUENCE RHEKT.SEQIDASIGNACION;