DROP TABLE RHEKT.TASUCURSALES CASCADE CONSTRAINTS PURGE;
DROP TABLE RHEKT.TAKITXCEDIS CASCADE CONSTRAINTS PURGE;
DROP TABLE RHEKT.TACEDIS CASCADE CONSTRAINTS PURGE;
DROP TABLE RHEKT.TAFUNCIONESXNEGOCIO CASCADE CONSTRAINTS PURGE;
DROP TABLE RHEKT.TASKUSXSUBKIT CASCADE CONSTRAINTS PURGE;
DROP TABLE RHEKT.TASUBKITSXKIT CASCADE CONSTRAINTS PURGE;
DROP TABLE RHEKT.TASUBKITS CASCADE CONSTRAINTS PURGE;
DROP TABLE RHEKT.TAKITUNIFORMES CASCADE CONSTRAINTS PURGE;

ALTER TABLE RHEKT.UNI_PRECIO_PEDIDO DROP COLUMN FISEMANASDESCTO;