INSERT INTO RHEKT.TAESTATUSREPOSICION(FIESTATUSREPOSICION, FCDESCRIPCION) VALUES (0, 'CANCELADA');
INSERT INTO RHEKT.TAESTATUSREPOSICION(FIESTATUSREPOSICION, FCDESCRIPCION) VALUES (10, 'SOLICITADA');
INSERT INTO RHEKT.TAESTATUSREPOSICION(FIESTATUSREPOSICION, FCDESCRIPCION) VALUES (20, 'AUTORIZADA CON COSTO');
INSERT INTO RHEKT.TAESTATUSREPOSICION(FIESTATUSREPOSICION, FCDESCRIPCION) VALUES (30, 'AUTORIZADA SIN COSTO');
INSERT INTO RHEKT.TAESTATUSREPOSICION(FIESTATUSREPOSICION, FCDESCRIPCION) VALUES (40, 'PEDIDO GENERADO');

/*++++++++++++++++++++++++++++++++++++++++++++++++*
 * CONFIGURACION DE NUEVO MANUAL DE IMAGEN
 *++++++++++++++++++++++++++++++++++++++++++++++++*/
UPDATE RHEKT.TAFUNCIONESXNEGOCIO SET FCMANUALDEIMAGEN = 'manualImagen/Diapositiva%02d.JPG|28' WHERE FCMANUALDEIMAGEN = 'manualImagen/Diapositiva%02d.jpg|26';

COMMIT;