INSERT INTO RHEKT.TACATSTATUSGRAL(FIIDSTATUSGRAL, FCDESCRIPCION) VALUES (10, 'SOLICITADO');
INSERT INTO RHEKT.TACATSTATUSGRAL(FIIDSTATUSGRAL, FCDESCRIPCION) VALUES (20, 'PARCIALMENTE ATENDIDO EN CD');
INSERT INTO RHEKT.TACATSTATUSGRAL(FIIDSTATUSGRAL, FCDESCRIPCION) VALUES (30, 'ATENDIDO EN CD');
INSERT INTO RHEKT.TACATSTATUSGRAL(FIIDSTATUSGRAL, FCDESCRIPCION) VALUES (40, 'PARCIALMENTE ENVIADO A TIENDA');
INSERT INTO RHEKT.TACATSTATUSGRAL(FIIDSTATUSGRAL, FCDESCRIPCION) VALUES (50, 'ENVIADO A TIENDA');
INSERT INTO RHEKT.TACATSTATUSGRAL(FIIDSTATUSGRAL, FCDESCRIPCION) VALUES (60, 'PARCIALMENTE RECIBIDO EN TIENDA');
INSERT INTO RHEKT.TACATSTATUSGRAL(FIIDSTATUSGRAL, FCDESCRIPCION) VALUES (70, 'RECIBIDO EN TIENDA');
INSERT INTO RHEKT.TACATSTATUSGRAL(FIIDSTATUSGRAL, FCDESCRIPCION) VALUES (80, 'PARCIALMENTE ENTREGADO');
INSERT INTO RHEKT.TACATSTATUSGRAL(FIIDSTATUSGRAL, FCDESCRIPCION) VALUES (90, 'ENTREGADO');


INSERT INTO RHEKT.TACATSTATUSDETALLE(FIIDSTATUSDETALLE, FCDESCRIPCION) VALUES (10, 'SOLICITADO');
INSERT INTO RHEKT.TACATSTATUSDETALLE(FIIDSTATUSDETALLE, FCDESCRIPCION) VALUES (20, 'GRABADO EN TIENDA');
INSERT INTO RHEKT.TACATSTATUSDETALLE(FIIDSTATUSDETALLE, FCDESCRIPCION) VALUES (30, 'ENVIADO A ABASTO');
INSERT INTO RHEKT.TACATSTATUSDETALLE(FIIDSTATUSDETALLE, FCDESCRIPCION) VALUES (40, 'ATENDIDO EN CD');
INSERT INTO RHEKT.TACATSTATUSDETALLE(FIIDSTATUSDETALLE, FCDESCRIPCION) VALUES (50, 'ENVIADO A TIENDA');
INSERT INTO RHEKT.TACATSTATUSDETALLE(FIIDSTATUSDETALLE, FCDESCRIPCION) VALUES (60, 'RECIBIDO EN TIENDA');
INSERT INTO RHEKT.TACATSTATUSDETALLE(FIIDSTATUSDETALLE, FCDESCRIPCION) VALUES (70, 'ENTREGADO');
INSERT INTO RHEKT.TACATSTATUSDETALLE(FIIDSTATUSDETALLE, FCDESCRIPCION) VALUES (00, 'CANCELADO');
INSERT INTO RHEKT.TACATSTATUSDETALLE(FIIDSTATUSDETALLE, FCDESCRIPCION) VALUES (-10, 'ERROR');

INSERT INTO RHEKT.TACATSTATUSASIGN(FIIDSTATUSASIGN, FCDESCRIPCION) VALUES (10, 'ASIGNADO');
INSERT INTO RHEKT.TACATSTATUSASIGN(FIIDSTATUSASIGN, FCDESCRIPCION) VALUES (20, 'ENTREGADO');
INSERT INTO RHEKT.TACATSTATUSASIGN(FIIDSTATUSASIGN, FCDESCRIPCION) VALUES (00, 'CANCELADO');

COMMIT;